### ISSUE TITLE
Error: no method or default for coercing "NULL" to "GRanges"

### ISSUE THREAD

**Issue by kmavrommatis** [lcalviell/ORFquant#2]
I have created a _for_ORFquant file by using the RiboseQC package (v1.1)
When I use the run_ORFquant function I get the error:

```
run_ORFquant(for_ORFquant_file="test_IgnoliaAligned.out.coord_for_ORFquant", annotation_file="test_1/gencode.annotation.gtf_Rannot",n_cores=3)


Loading annotation and Ribo-seq signal ... Wed Mar 18 05:58:12 2020
Loading annotation and Ribo-seq signal --- Done! Wed Mar 18 05:58:22 2020
Summoning ORFquant with 2565 P_sites positions over 329 genomic regions using 3 processor(s) ... Wed Mar 18 05:58:22 2020
Summoning ORFquant --- Done! Wed Mar 18 06:01:00 2020
Exporting ORFquant results ... Wed Mar 18 06:01:00 2020
Error in FUN(X[[i]], ...) : 
  no method or default for coercing "NULL" to "GRanges"
```

I get the same error if I try to specify the actual genes using the gene_id or gene_name argument. 

e.g.
```
run_ORFquant(for_ORFquant_file="test_IgnoliaAligned.out.coord_for_ORFquant", annotation_file="../test_1/gencode.annotation.gtf_Rannot",n_cores=3, gene_id=GTF_annotation$trann$gene_id)
```

am I missing something? 
Thanks

**Comment by lcalviell** [comment]
Hi Kostas, Thanks for the message.

Could you provide a reproducible example? e.g. the annotation files you used (gtf and 2bit) and the "for_ORFquant" file?

Thanks!

**Comment by kmavrommatis** [comment]
Sure, you can find the gtf and 2bit file, along with the for_ORFquant here:
https://www.dropbox.com/sh/2vlz1i8r4juqz3i/AAAjd5syiY13VnMa6CqYN2qoa?dl=0

The gtf & 2bit file were used to create the annotation with the function prepare_annotation from RiboseQC (v1.1)

```
prepare_annotation_files(annotation_directory = "test_1",
                         twobit_file = "genome.2bit",
                         gtf_file = "gencode.annotation.gtf" ,
                         scientific_name = "Homo.sapiens",
                         annotation_name = "gencode.v24",
                         export_bed_tables_TxDb = TRUE,
                         forge_BSgenome = TRUE,
                         create_TxDb = TRUE)
```

Subseqeuently I used RiboseQC to get the output :

```
RiboseQC_analysis(
		annotation_file = "test_1/gencode.annotation.gtf_Rannot",
                bam_file = "test_IgnoliaAligned.out.coord.bam",
		read_subset = TRUE,
		readlength_choice_method = "max_coverage",
		dest_names = "test_IgnoliaAligned.out.coord",
		rescue_all_rls =FALSE,
		fast_mode = TRUE, 
                write_tmp_files = FALSE,
		create_report = TRUE,
		sample_names = "test_IgnoliaAligned.out.coord",
		report_file = "test_IgnoliaAligned.out.coord.html", 
		extended_report = TRUE,
		pdf_plots = TRUE)

```
if that makes any difference the BAM file was created using STAR v 2.7.2d on an genome index coming from the same genome and annotation versions that were used for these steps.

Thanks in advance for your help

**Comment by kmavrommatis** [comment]
Hi, are there any news about this?
Thanks in advance for your help.

**Comment by lcalviell** [comment]
Hi, I'm running it right not, results soon!

**Comment by lcalviell** [comment]
Dear Kostas, I found the error:
unfortunately no ORFs were detected : (
Please check the quality and sub-codon resolution of your P-sites (e.g. inspecting the Ribo-seQC report).
I will edit the code to display a different message when this happens.

Best,
Lorenzo

**Comment by kmavrommatis** [comment]
Thanks for the response, 
I wonder though what the real reason for this is, since the data I used are coming from the Ignolia publication, and should have ORFs...

**Comment by lcalviell** [comment]
Dear Kostas, unfortunately different software require different data quality to reliably identify translated ORFs. There's plenty of datasets out there with such a resolution to perform de-novo ORF finding with ORFquant, probably including publications from the Ingolia lab. You might also want to inspect if there has been some problem during in data processing.
Again, inspecting the html report from Ribo-seQC might provide some help. 

Best,
Lorenzo

**Comment by kmavrommatis** [comment]
Thanks, indeed this particular dataset does not seem to have high quality values, judged by the RiboseqQC output. Trying with a different dataset, that shows better quality metrics seems to work and produce results (but check #3). 
However, I am a bit confused about the results.

Even with the low quality dataset, RiboseqQC returns a list of genes with RPKM and TPM values. There are no ORFs identified in those genes by ORFquant. Where would this discrepancy be attributed? And for downstream analysis, and evaluation of translational efficiency would it make sense to use RPKM/TPM from RiboseqQC or ORF-pM by ORFquant ?
Thanks again for your help
Kostas

**Comment by lcalviell** [comment]
Dear Kostas,

RiboseQC provides a table with counts,  RPKM and TPM values using annotated transcript and CDS structures (the ones present in your gtf file).
ORFquant performs de-novo ORF finding and quantification, thus providing (when possible) quantification of ORFs entirely detected using Ribo-seq data alone, without explicit guidance from existing CDS annotation (uses CDS annotation to determine positional annotation and "novelty" of detected ORFs).
If you are interested in performing TE analysis on annotated CDS regions, you can use count output by RiboseQC and use it with downstream software for Differential Expression Analysis, as described here: https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpmb.108.

Best,
Lorenzo

**Comment by kmavrommatis** [comment]
Thanks, that was my understanding as well, but I was struck by the disconnect/discrepancy between the numbers (TPMs or equivalent) between the methods, but I guess this can be explained by taking into account the differences in the algorithms and filtering.
Thanks again for your help
