### ISSUE TITLE
ORFquant stuck on  "Exporting ORFquant results"

### ISSUE THREAD

**Issue by jdcla** [lcalviell/ORFquant#24]
Hello,

My ORFquant installation keeps getting stuck on a singular dataset at the "Exporting ORFquant results" step. I've let it run for longer than a week and am now sure it is not simply in need of more processing time.

The "bam_out_tmp_ORFquant_results" seems to be complete.

**Comment by lcalviell** [comment]
Hi,

Could you please provide more info about your run, including the annotation you used? Also, could you share the "bam_out_tmp_ORFquant_results" file?

Thanks!

**Comment by jdcla** [comment]
Thank you for the quick response:

The "bam_out_tmp_ORFquant_results" can be found here: https://www.dropbox.com/scl/fi/sjw8mway77pqo52pxsczp/bam_out_tmp_ORFquant_results?rlkey=tl6bkfyh5mf8p67v6emr8uca2&dl=0

The data is derived from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144682
The files are derived from the RiboSeq data: Hs_H1_BG99_3D_d11_ctrl_Riboseq_replicate1_* (5 replicates)

I can't give much more details on the run itself, as no specific output that alludes to the freezing behavior is given. I can tell ORFquant successfully ran on multiple other data sets that were pre-processed in an identical way.

**Comment by jvandinter** [comment]
Hi all,

We have the same issue as Jim when we try to merge our "shallow" (initial sequencing run to check library quality, such as periodicity) and our corresponding "deep" runs with libraries of sufficient quality. Merging the shallow runs will work just fine, so it might seem to be a problem with a certain sample size? Anyhow, I still had the TMP results lying around so I linked them here. It has been run on a custom transcriptome assembly which we generated with prepare_annotation_files() function.

The download link will work for a week.

https://surfdrive.surf.nl/files/index.php/s/oGVvO3JOjdKANcZ

**Comment by jdcla** [comment]
> Hi,
> 
> Could you please provide more info about your run, including the annotation you used? Also, could you share the "bam_out_tmp_ORFquant_results" file?
> 
> Thanks!

Any chances this will be fixed in the near future, or you could provide me with the finalized file?

**Comment by calviellolab** [comment]
We're looking into it!

**Comment by lcalviell** [comment]
Hi everybody,

I think I solved the issue. Please re-install ORFquant 
`install_github(repo = "lcalviell/ORFquant")` 
and re-run it, unfortunately I don't have enough info to produce the files you need (I'd need to have genomes, annotation etc...) but it should work now.
Let me know how it goes!

**Comment by jdcla** [comment]
This seems to have solved the issue for me.

**Comment by jvandinter** [comment]
Unfortunately, this has not worked for us. We get the following cryptic error message after 100% completion:

> 100% completed
> Error in { :
>   task 103 failed - "1 elements in value to replace 0 elements"
> Calls: ORFquant_analysis -> run_ORFquant -> %dopar% -> <Anonymous>
> Execution halted

I have a slightly modified version of ORFquant so I can containerize it. This is how our ORFquant HTML function looks like:

```
create_ORFquant_html_report <- function(input_files, input_sample_names, output_file){
  
  # get input and output file paths
  input_files <- paste(normalizePath(dirname(input_files)),basename(input_files),sep="/")
  output_file <- paste(normalizePath(dirname(output_file)),basename(output_file),sep="/")
  
  # get path to RMarkdown file (to be rendered)
  rmd_path <- paste(system.file(package="ORFquant"),"/rmd/ORFquant_template.Rmd",sep="")
#######################################
  tmp_dir <- dirname(output_file)
#######################################
  
  sink(file = paste(output_file,"_ORFquant_report_output.txt",sep = ""))
  # render RMarkdown file > html report
  suppressWarnings(render(rmd_path, 
                          params = list(input_files = input_files,
                                        input_sample_names = input_sample_names),
                          output_file = output_file,
#######################################
                          intermediates_dir = tmp_dir))
#######################################
  sink()
}

```

Everything between the "#####" are the new additions, as the default temporary directory is in the R package folder, which is in the unwritable container. 

This is our orfquant_analysis function:

```
ORFquant_analysis <- function(for_ORFquant_file, ORFquant_output_file, ORFqua
nt_plot_data, rannot, cpu, html_report, sample_id) {

    print(for_ORFquant_file)

    if(!file.exists(ORFquant_output_file)) {

        run_ORFquant(for_ORFquant_file = for_ORFquant_file,
                     annotation_file = rannot,
                     n_cores = cpu,
                     prefix = ORFquant_out,
                     gene_name = NA,
                     gene_id = NA,
                     genomic_region = NA,
                     write_temp_files = T,
                     write_GTF_file = T,
                     write_protein_fasta = T,
                     interactive = T,
                     stn.orf_find.all_starts = T,
                     stn.orf_find.nostarts = F,
                     stn.orf_find.start_sel_cutoff = NA,
                     stn.orf_find.start_sel_cutoff_ave = 0.5,
                     stn.orf_find.cutoff_fr_ave = 0.5,
                     stn.orf_quant.cutoff_cums = NA,
                     stn.orf_quant.cutoff_pct = 2,
                     stn.orf_quant.cutoff_P_sites = 10,
                     unique_reads_only = F,
                     canonical_start_only = T,
                     stn.orf_quant.scaling = "total_Psites"
                     )
    } else {
        print("ORFquant file already exists")
    }

    plot_ORFquant_results(for_ORFquant_file = for_ORFquant_file,
        ORFquant_output_file = ORFquant_output_file,
        annotation_file = rannot
        )

    create_ORFquant_html_report(input_files = ORFquant_plot_data,
        input_sample_name = sample_id,
        output_file= html_report
        )
}
```

Would you have any idea what would've caused this?

**Comment by jvandinter** [comment]
To get back to this issue: ORFquant completed successfully when we removed the P-site cut-off which we had in place. 

`stn.orf_quant.cutoff_P_sites = 10`
To
`stn.orf_quant.cutoff_P_sites = NA`

**Comment by bioinfoSE** [comment]
Hello Lorenzo,

I have received the following error while running ORFquant, which seems similar to the one jvandinter posted on Jan 10, 2024.

```
Summoning ORFquant with 744013 P_sites positions over 2255 genomic regions using 16 processor(s) ...  
0% completed
10% completed
30% completed
20% completed
40% completed
50% completed
60% completed
70% completed
80% completed
90% completed
100% completed
Error in { :
  task 1355 failed - "1 elements in value to replace 0 elements"
Calls: <Anonymous> -> %dopar% -> <Anonymous>
Execution halted
```

This was executed within a Nextflow pipeline using the following wrapper script -

```
#!/bin/bash

Rscript='/scratch/users/bioinfoSE/Tools/R-4.5.2/R-4.5.2/bin/Rscript'
Dir="/scratch/users/bioinfoSE/Projects/code/ORF/ORFquant/bin"

Rannot="$1"
for_orfquant="$2"
prefix="$3"

"$Rscript" "${Dir}/ORFquant.R" "$Rannot" "$for_orfquant" "$prefix"
```

and the R script:

```
#!/usr/bin/env Rscript

suppressPackageStartupMessages(library(ORFquant))

args <- commandArgs(trailingOnly = TRUE)

if (length(args) != 3 ) {
        stop("Usage: ORFquant.R <Rannot> <for_orfquant> <prefix>")
}

Rannot          <- args[1]
for_orfquant    <- args[2]
prefix          <- args[3]

ORFquant::run_ORFquant(for_ORFquant_file = for_orfquant, annotation_file = Rannot, prefix = prefix, n_cores = 16, stn.orf_quant.cutoff_P_sites = NA)
```
Interestingly, this issue does not occur for all samples.

The input BAM files are split by chromosome prior to running `prepare_for_ORFquant()`. 
To rule out the dopar error, I ran ORFquant using `n_cores = 1` on a single sample on RStudio server and received a similar error - 

```
Error in `[[<-`(`*tmp*`, name, value = "shared") : 
  1 elements in value to replace 0 elements
```

Do you have any suggestions on how to debug or resolve this?

Thanks,
Shruti
