### ISSUE TITLE
Clarify the difference between SaTAnn and ORFquant

### ISSUE THREAD

**Issue by nh13** [lcalviell/ORFquant#5]
From their respective READMEs:

* ORFquant:
> ... R package that aims at detecting and quantifiying ORF translation on complex transcriptomes using Ribo-seq data
* SaTAnn
> R package that aims at detecting and quantifiying ORF translation on complex transcriptomes using Ribo-seq data

What are the advantages and differences of one or the other, should we prefer ORFquant, etc.

**Comment by lcalviell** [comment]
Hi,

SaTAnn is the original package, later modified and upgraded to ORFquant. Will update the README. Thanks!

**Comment by nh13** [comment]
Awesome, thank you for all your hard work as well! I read most of your dissertation and follow on work, it was very clear. Thanks!
